// <auto-generated />
namespace Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Campo_CEP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campo_CEP));
        
        string IMigrationMetadata.Id
        {
            get { return "201812180238594_Campo_CEP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
